### ISSUE TITLE
Typos, add domainName to keypath in signingtable, add checks for missing pillar data

### ISSUE THREAD

**Issue by campbellmc** [saltstack-formulas/opendkim-formula#1]
Hi,
There are a few issues/typos in this formula which will stop it from working in Signing Mode.
- Missing `domainName` in keypath in signing table
- spelling of KeyTable (KeyTables)
- pillar example should have `file:` or `file:` against Signing Table path
- not checking for missing pillar data (really should have default values to avoid these problems)
- includes missing in sls files so that they can be run separately (requires/watch issues)

Have fixed them in a fork.

**Comment by javierbertoli** [comment]
Hi @campbellmc, better late than ever, I guess. If you're still using this formula's fork, mind you submit a PR so we can update it?

**Comment by campbellmc** [comment]
I think my fork diverges a little too much to be able to create a useful PR for you.

**Comment by couilllard45682** [comment]
PR #3 is created to fix every issue mentioned here except for : 
- not checking for missing pillar data (really should have default values to avoid these problems)

**Comment by couilllard45682** [comment]
@campbellmc  Are you willing to reopen the issue to get this merged?
Thanks
